Avoid recursive role and action group
opensearch-project/security pull request #1404
Opened 2021-08-13 21:11 UTC by cliu123

##  opensearch-security pull request intake form
_Please provide as much details as possible to get feedback/acceptance on your PR quickly_

 
 1. __Category:__ (_Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation_)
 Bug fix
 
 
 2. __Github Issue # or road-map entry, if available:__
#1389 

 3. __Description of changes:__
 If recursive action groups exist, exception is thrown while loading securityconfigs into memory.

 4. __Why these changes are required?__ 
Recursive action groups cause `StackOverflowError` while being loaded to memory.

 5. __What is the old behavior before changes and new behavior after changes?__ (_Please add any example/logs/screen-shot if available_)
Recursive action groups cause `StackOverflowError` while security configs are being loaded to memory. 

 6. __Testing done:__ (_Please provide details of testing done: Unit testing, integration testing and manual testing_)
 UT and Manual testing
 
 
 7. __TO-DOs, if any:__ (_Please describe pending items and provide Github issues# for each of them_)

 8. __Is it backport from main branch?__ (_If yes, please add backport PR # and commits #_)

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2021-08-14 05:57 UTC, vrozov requested changes
-1: it is too late to raise exception **after** invalid configuration is loaded into the security index. It is necessary to validate configuration **before** it is written to the security index.

2021-08-14 05:57 UTC, vrozov commented on src/main/java/org/opensearch/security/securityconf/ConfigModelV7.java
> +                        if (perm == entry) {
Not a proper way to compare `Strings` in Java.
Not a proper way to identify recursion except for a self reference trivial case.

2021-08-14 05:57 UTC, vrozov commented on src/test/java/org/opensearch/security/SecurityRolesTests.java
> +		HttpResponse resc = rh.executeGetRequest("_cat/nodes?pretty", encodeBasicHeader("recursive_internal_user", "nagilum"));
Not a proper test, it succeeds even without code changes in `ConfigModelV7.java`.

2021-09-19 05:51 UTC, dhiAmzn commented
This only takes care of cases where action group is self referenced in its allowed actions. It will not take care of cases where there's a circular dependency such as:

```
AG_1:
  allowed_actions:
  - "AG_2"

AG_2:
  allowed_actions:
  - "AG_1"
```

2021-11-03 17:16 UTC, closed without merging