Adding auto delete workflow for backport branches
opensearch-project/security pull request #1604
Opened 2022-02-11 02:50 UTC by VachaShah

Signed-off-by: Vacha Shah <vachshah@amazon.com>

### Description
Workflow to automatically delete the branches created by the [backport action ](https://github.com/opensearch-project/k-NN/blob/main/.github/workflows/backport.yml)of type `backport/*`.

This PR needs to be backported to release branches so that the auto delete runs on backport PRs created for those branches.

* Category: Enhancement
* Why these changes are required?
In order to automatically delete branches created by the backport workflow.
* What is the old behavior before changes and new behavior after changes?
Branches have to be manually deleted after auto backport PR is merged without this change.

### Issues Resolved
[List any issues this PR will resolve]

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
This works in OpenSearch repo.

### Check List
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-02-11 13:28 UTC, davidlago submitted a review, later dismissed

2022-02-11 16:28 UTC, peternied requested changes

2022-02-11 16:28 UTC, peternied commented on .github/workflows/delete_backport_branch.yml
> +        uses: SvanBoxel/delete-merged-branch@main
We should not use branch references for security reasons, this should be a commit id or tag to be sure only the approved version of the plugin is running

2022-02-15 14:37 UTC, davidlago approved these changes

2022-02-15 15:21 UTC, peternied approved these changes
Thanks!

2022-02-15 15:21 UTC, merged

2022-02-15 19:07 UTC, VachaShah commented
@davidlago @peternied This PR needs to be backported to the release branches so that this workflow can run when PRs are backported to release branches. Which release branches would those be? I can add appropriate labels on this PR so it can be auto-backported.

2022-02-15 19:10 UTC, peternied commented
@davidlago you know better than I at this point, but I promise I'll pay attention

2022-02-15 19:32 UTC, davidlago commented
Good catch! We only have `main` which is `1.3.0-SNAPSHOT` but we do have branch `1.2` whose head is currently `1.2.4-SNAPSHOT` so we should indeed backport to that. @peternied could you also please check whether we need a similar change for the dashboards security plugin?

2022-02-15 19:39 UTC, peternied commented
https://github.com/opensearch-project/security-dashboards-plugin/pull/901 is tracking this change getting merged.