Updates the folder structure for build artifacts
opensearch-project/security pull request #1749
Opened 2022-04-07 15:39 UTC by DarshitChanpura

### Description
Updates the folder structure created during build to follow the suggested structure.

* Category - Maintenance

### Issues Resolved
* Resolves #1673 

### Check List
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-07 16:08 UTC, peternied commented
Looks like the classpath isn't resolving correctly:

```
fatal error in thread [main], exiting
java.lang.NoClassDefFoundError: io/netty/util/internal/PlatformDependent
	at org.opensearch.security.ssl.OpenSearchSecuritySSLPlugin.<clinit>(OpenSearchSecuritySSLPlugin.java:94)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:[49](https://github.com/opensearch-project/security/runs/5871493875?check_suite_focus=true#step:11:49)9)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.opensearch.plugins.PluginsService.loadPlugin(PluginsService.java:776)
	at org.opensearch.plugins.PluginsService.loadBundle(PluginsService.java:725)
	at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:[52](https://github.com/opensearch-project/security/runs/5871493875?check_suite_focus=true#step:11:52)7)
	at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:190)
	at org.opensearch.node.Node.<init>(Node.java:406)
	at org.opensearch.node.Node.<init>(Node.java:329)
	at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
	at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
	at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
	at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
	at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
	at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
	at org.opensearch.cli.Command.main(Command.java:101)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
	at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)
Caused by: java.lang.ClassNotFoundException: io.netty.util.internal.PlatformDependent
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:[58](https://github.com/opensearch-project/security/runs/5871493875?check_suite_focus=true#step:11:58)7)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:8[72](https://github.com/opensearch-project/security/runs/5871493875?check_suite_focus=true#step:11:72))
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 22 more
```

2022-04-08 22:56 UTC, peternied commented
@DarshitChanpura Lets close this pull request, it looks like the build is broken and the tools/bin issue is going to be a problem

2022-04-14 10:02 UTC, davidlago commented
is it intentional that the log4j change is part of this PR?

2022-04-14 16:42 UTC, DarshitChanpura commented
> is it intentional that the log4j change is part of this PR?

Nope...I have fixed that change now

2022-04-14 18:00 UTC, DarshitChanpura commented
White-source check failed with this check: https://github.com/opensearch-project/security/pull/1749/checks?check_run_id=6027602013
should we fix it in this branch?

2022-04-14 18:04 UTC, davidlago commented
I'd bump it in a separate one (did whitesource auto-create a PR for this?) and then rebase this one

2022-04-14 18:09 UTC, peternied requested changes
@DarshitChanpura do you have a before/after layout for the plugin so we can confirm its the expected layout?

There are many more places that need adjustment, from a [search in this codebase](https://github.com/opensearch-project/security/search?p=3&q=securityconfig) (which is hard to parse), I see some of the following:

https://github.com/opensearch-project/security/blob/74618eb5be4e587fe7d015d8ae15a3269bbce78c/tools/install_demo_configuration.sh#L420

https://github.com/opensearch-project/security/blob/54a920b20bd520f25aef328c1bb4997b325f46ce/src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java#L76

Also, please create an issue in the documentation website to update all the callouts as well, search on that codebase https://github.com/opensearch-project/documentation-website/search?q=securityconfig

2022-04-14 18:39 UTC, DarshitChanpura commented
> @DarshitChanpura do you have a before/after layout for the plugin so we can confirm its the expected layout?
> 
> There are many more places that need adjustment, from a [search in this codebase](https://github.com/opensearch-project/security/search?p=3&q=securityconfig) (which is hard to parse), I see some of the following:
> 
> https://github.com/opensearch-project/security/blob/74618eb5be4e587fe7d015d8ae15a3269bbce78c/tools/install_demo_configuration.sh#L420
> 
> https://github.com/opensearch-project/security/blob/54a920b20bd520f25aef328c1bb4997b325f46ce/src/test/java/org/opensearch/security/test/helper/cluster/ClusterHelper.java#L76


We have a folder structure mismatch when following different installation formats:
1. When we install using `./opensearch-plugin install`:
```
OpenSearch
│
└─── config
│     │
      └─── opensearch-security
│          │   
           └─── *.yml
```

2. When we install using Dev guide:
```
OpenSearch
│
└─── plugins
│     │
      └─── opensearch-security
│          │   
           └─── config (folder renamed from `securityconfig`)
|               │   
                └─── *.yml
```

I'll update the changes according to scenario 1 and push again.

2022-04-14 19:34 UTC, DarshitChanpura commented
The [CVE](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2022-22968) was introduced with this PR, alongwith two other CVEs: https://github.com/opensearch-project/security/pull/1735
And whitesource didn't catch it because whitesource check didn't run: https://github.com/opensearch-project/security/runs/5959469645

We should create a PR to fix all 3

2022-04-14 20:25 UTC, peternied commented
> The [CVE](https://www.whitesourcesoftware.com/vulnerability-database/CVE-2022-22968) was introduced with this PR, alongwith two other CVEs: #1735 And whitesource didn't catch it because whitesource check didn't run: https://github.com/opensearch-project/security/runs/5959469645
> 
> We should create a PR to fix all 3

We can do that out of band of this PR, since this PR did not add any new dependencies.  We don't need to block this change if we are following up separately.

If this PR did add the items that were flagged by whitesource then it would be a case to prevent the PR from merging until it was resolved.

2022-04-15 12:51 UTC, davidlago commented
I agree with @peternied, let's go ahead and merge... I just saw the auto-opened issue by whitesource https://github.com/opensearch-project/security/issues/1765

2022-04-15 12:51 UTC, davidlago approved these changes

2022-04-15 15:17 UTC, DarshitChanpura commented
@cliu123 can I get a second review on this?

2022-04-15 20:18 UTC, cliu123 approved these changes

2022-04-15 22:31 UTC, merged