Change 2.0-alpha1 to 2.0-rc1.
opensearch-project/security pull request #1764
Opened 2022-04-14 17:57 UTC by dblock

Following https://github.com/opensearch-project/opensearch-build/pull/1863, change 2.0-alpha1 to 2.0-rc1.

2022-04-14 18:20 UTC, peternied commented
@dblock This is a chicken v. egg build problem.  The security plugin uses the OpenSearch min tar to make sure it can be installed.  Until we've got a rc1 version of OpenSearch min our CI check won't pass.

Option 1) remove security plugin from the manifest.  Cleanest approach for build safety with the tradeoff of consuming a lot of time during this transition phase.

Option 2) bypass the CI check and cross fingers that the new build doesn't have any unexpected issues.

My preference is towards option 1 with the understanding it will slow down the whole rollout.  This will ensure only correctly building plugins are included in the build, avoiding an utterly broken build.

Note; These problems are magnified in security-dashboards-plugin as it depends on a full distribution build for its CI checks.

2022-04-15 15:36 UTC, DarshitChanpura commented
> @dblock This is a chicken v. egg build problem. The security plugin uses the OpenSearch min tar to make sure it can be installed. Until we've got a rc1 version of OpenSearch min our CI check won't pass.
> 
> Option 1) remove security plugin from the manifest. Cleanest approach for build safety with the tradeoff of consuming a lot of time during this transition phase.
> 
> Option 2) bypass the CI check and cross fingers that the new build doesn't have any unexpected issues.
> 
> My preference is towards option 1 with the understanding it will slow down the whole rollout. This will ensure only correctly building plugins are included in the build, avoiding an utterly broken build.
> 
> Note; These problems are magnified in security-dashboards-plugin as it depends on a full distribution build for its CI checks.

I have created a PR to address option 1. https://github.com/opensearch-project/opensearch-build/pull/1977

2022-04-15 16:15 UTC, dblock commented
Once there's a successful distribution rc1 build CI will turn green here, let's retry later today.

2022-04-15 22:47 UTC, DarshitChanpura commented
Thank you @dblock !

2022-04-15 22:52 UTC, peterzhuamazon requested changes
Wrong edit changelog

2022-04-15 22:52 UTC, peterzhuamazon commented on release-notes/opensearch-security.release-notes-1.0.0.0-beta1.md
> +* Consume OpenSearch 1.0.0-rc1 ([#1132](https://github.com/opensearch-project/security/pull/1132))
You should not change this @dblock

2022-04-15 23:18 UTC, DarshitChanpura approved these changes

2022-04-15 23:18 UTC, peterzhuamazon approved these changes

2022-04-15 23:28 UTC, merged