More thorough and explicit user examples
opensearch-project/security pull request #1784
Opened 2022-04-22 23:09 UTC by reshippie

### Description
* Category: Documentation
* Why these changes are required?  The documentation was incomplete and confusing to some.
* What is the old behavior before changes and new behavior after changes?  Same behavior, but better documentation for users transitioning from ODfE to Opensearch.

### Issues Resolved
https://github.com/opensearch-project/security/issues/1766

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/       OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-04-25 18:37 UTC, peternied requested changes
Thanks for creating this PR, it looks pretty good thank you for the expanded language. 

The only issue preventing this change from being merged is the DCO signing, you can follow these steps to remedy https://github.com/opensearch-project/security/pull/1784/checkscheck_run_id=6136236229

2022-05-02 17:25 UTC, reshippie commented
Looks like everything is good to go now.

2022-05-02 17:35 UTC, peternied approved these changes

2022-05-03 17:52 UTC, DarshitChanpura approved these changes

2022-05-03 17:53 UTC, merged