Password setup tool for built-in users
opensearch-project/security pull request #1836
Opened 2022-05-11 21:19 UTC by setiah

### Description
This PR primarily provides new password setup tool for setting up passwords for inbuilt security users (admin, kibanaserver, etc.) and also provides a new unified interface for extending tooling in opensearch-security. 

> Details of all the changes
1. Provides a new unified interface to simplify and extend tooling in opensearch-security.
2. Adds setup-password functionality to allow users to setup secure passwords for built-in users, instead of relying on weak defaults such as admin:admin. The functionality is provided in both manual and auto mode for auto-password generation.
3. Adds default secure password policy to opensearch.yml

> What is the old behavior before changes and new behavior after changes?

In the old behavior, users had to update the internal_users.yml file on all nodes with the hash of the password to change the passwords from admin/admin. While that still works, with the new tool, they can simply run the tool to setup secure passwords after installation. The tool runs as `opensearch-admin setup-passwords [--auto]` or to setup policy compliant passwords for inbuilt users (both manually and automatically). It can be extended to support other functions such as `setup-certificates`, `reload-configs`, through its simplified extensible interface. 

### Issues Resolved
#1686 

Is this a backport? If so, please add backport PR # and/or commits #
No
### Testing
Unit testing, Manual testing

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-05-17 20:23 UTC, setiah commented
@peternied can you help with reviewing this PR? 
cc: @ryanbogan

2022-05-17 20:23 UTC, setiah commented
@peternied can you help with reviewing this PR? 
cc: @ryanbogan

2022-05-24 22:38 UTC, CEHENKLE commented
@opensearch-project/security Hey folks -- can we get some code review luv over here?  

Thanks :) 

/C

2022-05-25 19:40 UTC, cliu123 commented on src/test/java/org/opensearch/security/SlowIntegrationTests.java
> +
Please remove this empty line if not necessary.

2022-05-26 16:05 UTC, peternied requested changes
Thanks for the pull request.  Making sure that new clusters have strong security posture is an important space for us.

This pull request changes the responsibility of the security plugin by adding a new OpenSearch-Admin script.  This is a public interface in the security repository that over time will likely need to be deprecated based on de-emphasizing security as a plugin.  We should avoid this, I would recommend baking these changes into a cluster initialization process.

Accepting custom passwords creates the opportunity for bad password practices.  OpenSearch would have a better posture if we had a standard password generation of say 20+ characters of entropy.  This could be done with modifications to the existing create user API or as part of the initialization process to standard out.

Please reduce the scope of this PR to an automatic (strong) password generation during the initialization process, and extract the admin tool/script creation into a separate draft PR so we can have that larger discussion over there, and weigh the pros and cons of adding a tool that will need to be deprecated vs postponing that effort until we have a broader plan for admin tools moving forward.

2022-06-07 00:09 UTC, setiah commented
@peternied 

There is a separate [issue](https://github.com/opensearch-project/security/issues/1787) tracking auto-password setup during cluster bootstrap, which leverages the PasswordSetup logic added by this tool to autogenerate passwords. But passwords are not just setup during the first time setup. They also need to be rotated many times during the lifecycle of a cluster based on security needs of an organization. This tool provides an easy way to for cluster administrator to set the passwords first time (until we have [this](https://github.com/opensearch-project/security/issues/1787)) and rotate/update them later. Hence it would be helpful.

>This pull request changes the responsibility of the security plugin by adding a new OpenSearch-Admin script. This is a public interface in the security repository that over time will likely need to be deprecated based on de-emphasizing security as a plugin. 

The public interface is for Security plugin tooling and is not needed in other plugins. All tools in Security plugin (hasher, securityadmin, install_demo_configurations, etc.) can extend this interface to inherit some common functions, and just build their business logic. This will enable java-fying the security plugin tools so they are unit testable like code, unlike some shell tools in security plugin repo today that need to be validated manually. Happy to consider if you have any other suggestions for the tool name.

>Accepting custom passwords creates the opportunity for bad password practices. This could be done with modifications to the existing create user API or as part of the initialization process to standard out.

I think you missed this change mentioned in the PR description - "Adds default secure password policy to opensearch.yml". The custom passwords are validated against this default secure password policy that is being adding with this change. If the password is not policy compliant, it gets rejected. 
Lack of a default secure password policy is a gap today which allows users to create weak passwords 

I'd request you to take a look again.

2022-06-07 19:02 UTC, peternied commented
> This tool provides an easy way to for cluster administrator to set the passwords first time (until we have https://github.com/opensearch-project/security/issues/1787) and rotate/update them later. Hence it would be helpful.

The security plugin already has an API, there is no extra burden for documentation, maintenance or release management.  A new endpoint such as  `PUT user/{user}/rotateCredentials`, or improving existing endpoints for this scenario seems very reasonable.  Exposing this functionality with an API expands the utility so admins could make API calls directly, use the Dashboard UX, or use another plugin to go through the same workflow.  If this is built as a tool its utility is limited, lets build this functionality so it can be reused.  Is there a reason to limit the functionality?

> I think you missed this change mentioned in the PR description - "Adds default secure password policy to opensearch.yml". 

This change was done in the `tools/install_demo_configuration.sh` file, outside of the recommended configuration.  There would be much more benefit to make this change as part of the security default configuration.  What do you think about separating password policy into another pull request?

2022-06-21 21:57 UTC, setiah commented
> The security plugin already has an API, there is no extra burden for documentation, maintenance or release management. A new endpoint such as `PUT user/{user}/rotateCredentials`, or improving existing endpoints for this scenario seems very reasonable. Exposing this functionality with an API expands the utility so admins could make API calls directly, use the Dashboard UX, or use another plugin to go through the same workflow. If this is built as a tool its utility is limited, lets build this functionality so it can be reused. Is there a reason to limit the functionality?

The functionality already exists today with a PATCH API. The tool just builds on the capability of existing PATCH API to simplify password setup process for all internal users. I do think there is value in having a tool based mechanism over and above REST API as it makes life easier for users. 


> This change was done in the `tools/install_demo_configuration.sh` file, outside of the recommended configuration. There would be much more benefit to make this change as part of the security default configuration. What do you think about separating password policy into another pull request?

I'm okay with this suggestion.

2022-06-23 15:27 UTC, closed without merging