Staging for version increment automation
opensearch-project/security pull request #1932
Opened 2022-07-10 22:11 UTC by prudhvigodithi

Signed-off-by: pgodithi <pgodithi@amazon.com>

### Description
This is the staging PR for to execute workflows that auto raise the version increment PR's
Example: https://github.com/prudhvigodithi/security/pull/1

### Issues Resolved
Part of: https://github.com/opensearch-project/opensearch-build/issues/1375
From solution: https://github.com/opensearch-project/opensearch-build/issues/1375#issuecomment-1159476686
Related issue: https://github.com/opensearch-project/security/issues/1930

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
Example: https://github.com/prudhvigodithi/security/pull/1

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-10 22:58 UTC, prudhvigodithi commented
Referred old 2.x version increment PR: https://github.com/opensearch-project/security/pull/1881
@dblock  @bbarani

2022-07-11 17:09 UTC, peternied requested changes
Before we merge this change should have a test to ensure its functionality.

2022-07-12 00:51 UTC, prudhvigodithi commented on build.gradle
> +task versionIncrement {
Added @peternied can you please check.
Thank you

2022-07-12 14:09 UTC, peternied commented on .github/workflows/ci.yml
> +    - run: ./gradlew clean versionIncrement -DnewVersion=3.0.0-SNAPSHOT
This executes the command, but doesn't verify any outcome.  

What do you think about adding a execution of the gradle task `assemble`, check the artifact is version X, then run the `versionIncrement` task, then `assemble` and check its version X+1

2022-07-12 22:53 UTC, prudhvigodithi commented
Renaming to task updateVersion following https://github.com/opensearch-project/opensearch-plugin-template-java/pull/32.

2022-07-14 17:54 UTC, DarshitChanpura requested changes
This looks good. I agree with Peter's ask on testing to verify whether this change would work, if it is possible.

2022-07-25 16:17 UTC, prudhvigodithi commented
> @prudhvigodithi Do you need any help with this?

Hey @peternied I should be pushing the requested change by end of today, just got pulled away from this :)

2022-07-26 03:07 UTC, prudhvigodithi commented
Hey @peternied I have updated the CI workflow running the task `updateVersion` with an increment of `majorVersion + 1`. Please check
Thank you 
https://github.com/opensearch-project/security/runs/7512662131?check_suite_focus=true
@bbarani

2022-07-26 20:44 UTC, bbarani commented
@davidlago @peternied @DarshitChanpura  Can you please review this PR soon?

2022-07-26 20:46 UTC, peternied approved these changes
Thanks!

2022-08-01 16:17 UTC, DarshitChanpura reviewed
Thank you @prudhvigodithi !

2022-08-01 16:17 UTC, DarshitChanpura approved these changes
Thank you @prudhvigodithi !

2022-08-01 16:25 UTC, merged

2022-08-15 12:36 UTC, prudhvigodithi commented
Hey @peternied I see the following PR is closed https://github.com/opensearch-project/security/pull/1933, but this change is not backported to 1.x (1.3) branches, can you please take a look?

Thank you

2022-08-15 15:42 UTC, peternied commented
@prudhvigodithi Could you double check https://github.com/opensearch-project/security/pull/2029 and make sure it will work as expected?