Update to Gradle 7.5
opensearch-project/security pull request #1963
Opened 2022-07-25 18:28 UTC by reta

Signed-off-by: Andriy Redko <andriy.redko@aiven.io>

### Description
 Update to Gradle 7.5

### Issues Resolved
Closes https://github.com/opensearch-project/security/issues/1962

### Testing
N/A

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [X] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-07-25 18:35 UTC, peternied commented on build.gradle
> -        opensearch_version = System.getProperty("opensearch.version", "2.1.0-SNAPSHOT")
https://github.com/opensearch-project/security/pull/1948 is already in flight to update to 2.2 - which should be merged shortly.  Once that is done lets rebase to update to the new gradle version

2022-07-25 18:36 UTC, peternied requested changes

2022-07-25 18:36 UTC, peternied commented on gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-7.4.2-all.zip
There is a second gradle-wrapper.properties at https://github.com/opensearch-project/security/blob/main/bwc-test/gradle/wrapper/gradle-wrapper.properties

2022-07-26 16:27 UTC, peternied commented
https://github.com/opensearch-project/security/pull/1948 has been merged, @reta could you rebase?  You should only need the changes to the gradle version

2022-07-26 16:46 UTC, reta commented
> #1948 has been merged, @reta could you rebase? You should only need the changes to the gradle version

Yep, on it, thanks @peternied !

2022-07-26 17:27 UTC, peternied approved these changes
Thanks for the update!

2022-07-26 18:29 UTC, cliu123 approved these changes

2022-07-26 18:29 UTC, merged