Allow custom return attributes
opensearch-project/security pull request #2093
Opened 2022-09-16 08:49 UTC by Martin-Kemp

Signed-off-by: Martin Kemp <martin_leon.kemp@mercedes-benz.com>

### Description
Allows specifying which attributes to request from the ldap server.
* Category: New feature
* Why these changes are required?
It can be a security risk to request more attributes than needed from an ldap server.
* What is the old behavior before changes and new behavior after changes?
All attributes are requested.

### Issues Resolved
https://github.com/opensearch-project/security/issues/2032

Is this a backport? If so, please add backport PR # and/or commits #
No

### Testing
Manual testing with local ldap server. I made sure default behavior remains the same.
Updated unit tests.
This functionality is not tested directly with unit test, I can add one if needed.

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-16 16:47 UTC, peternied requested changes
Thanks for the contribution, allows happy to see a straight forward solution to a problem, good work!

To get this merged there are two outstanding items, 

### Test(s) for the new functionality

> This functionality is not tested directly with unit test, I can add one if needed.

Could you please add this functionality?

### CI failures
```
> Task :testClasses
Error: eckstyle] [ERROR] /home/runner/work/security/security/src/main/java/com/amazon/dlic/auth/ldap2/LDAPUserSearcher.java:20:8: Unused import - java.util.Arrays. [UnusedImports]

Error: eckstyle] [ERROR] /home/runner/work/security/security/src/main/java/com/amazon/dlic/auth/ldap2/LDAPUserSearcher.java:29:8: Unused import - org.ldaptive.ReturnAttributes. [UnusedImports]
> Task :checkstyleMain

> Task :checkstyleMain FAILED
```
_See https://github.com/opensearch-project/security/actions/runs/3066577438/jobs/4956644926_

Once these are resolved, it looks good to me.

2022-09-16 18:15 UTC, Martin-Kemp commented
> Could you please add this functionality?


Sure, will do next week. Thanks for reviewing.

2022-09-26 14:50 UTC, cwperks approved these changes
Thank you for your contribution @Martin-Kemp and for adding tests for this functionality!

2022-09-26 22:44 UTC, peternied approved these changes
Thanks for the contribution!

2022-09-26 22:45 UTC, merged