Updates jackson version to be in sync with core
opensearch-project/security pull request #2128
Opened 2022-09-29 20:40 UTC by DarshitChanpura

### Issues Resolved
* Related to #2124 

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-29 20:53 UTC, cwperks approved these changes

2022-09-29 21:18 UTC, peternied requested changes
We don't update 1.x, its a dead end branch.  Can this change be pointed against main and backported?  If not, please make the change against `1.3`

2022-09-30 14:05 UTC, cwperks commented
@DarshitChanpura Please re-base this change against 1.3. This change will be included in 1.3.6 and needs to get merged in today as EOD today is code freeze for 1.3.6.

2022-09-30 15:08 UTC, cwperks approved these changes

2022-09-30 16:07 UTC, peternied commented
Retriggering CI

2022-09-30 18:15 UTC, merged