[Backport 1.0] Username validation for special characters (#2277)
opensearch-project/security pull request #2330
Opened 2022-12-13 06:54 UTC by rutuja-amazon

### Description
 Username validation for special characters (#2277)
 
 * Only prevent user creation on colon characters, separate out tests

 Signed-off-by: Rutuja Surve [rutuja@amazon.com](mailto:rutuja@amazon.com)
 Signed-off-by: Rutuja Surve [110013621+rutuja-amazon@users.noreply.github.com](mailto:110013621+rutuja-amazon@users.noreply.github.com) 
Signed-off-by: Peter Nied [petern@amazon.com](mailto:petern@amazon.com) 
Co-authored-by: Peter Nied [petern@amazon.com](mailto:petern@amazon.com) (cherry picked from commit [efbc48b](https://github.com/opensearch-project/security/commit/efbc48b405ff6ff372c4821aa15c53fc50a409a3))

2022-12-13 16:15 UTC, peternied requested changes
Looks like the CI was canceled/failed and no results were generated from tests.  When we can see that test results working, modulo intermittent failures, the maintainers will merge this change.  Thanks!

2023-01-03 22:57 UTC, peternied commented
@rutuja-amazon I've restarted the tests - could you look into the failures if there are any?

2023-01-04 05:57 UTC, rutuja-amazon commented
@peternied CI is still failing.
Could we re-trigger the test for PR for 1.1 backport as well?

2023-01-04 16:33 UTC, peternied commented
> @peternied CI is still failing. Could we re-trigger the test for PR for 1.1 backport as well?

@rutuja-amazon CI isn't building at all, could you look into the failure [[link](https://github.com/opensearch-project/security/actions/runs/3683033519/jobs/6525242342)] if you'd like this change merged?  While bypassing flaky tests is typical in our v1 series of branches merging without a build seems rife for problems consuming this or future backports.

The maintainers do not support these older versions directly, but would happily accept additional changes if you'd like to fix the issues seen here.

2023-01-24 19:07 UTC, peternied commented
@rutuja-amazon I haven't seen updates for a while, I'm going to close out this pull request, please let me know if you'd like me to reopen it.

2023-03-17 09:18 UTC, rutuja-amazon commented
Hi @peternied , can we re-open to PR to re-run the CI pipeline, I'm unable to see the re-open option

2023-03-21 22:08 UTC, peternied commented
Not sure what caused the CI failure earlier as logs were deleted, re-running the test to ensure everything is cleanly passing

2023-03-22 13:08 UTC, peternied commented
@opensearch-project/security Figured out what was making these logs harder to read, and posted a stack overflow question / answer to help others.  Please take a look and comment or `+1` if you think it is useful.

- [GitHub Action job step failed with `Error: The log was not found.` message instead of expected log files](https://stackoverflow.com/questions/75812628/github-action-job-step-failed-with-error-the-log-was-not-found-message-inste)

2023-03-22 19:42 UTC, peternied approved these changes

2023-03-22 19:42 UTC, merged