Changing logging type to give warning for basic auth with no creds
opensearch-project/security pull request #2347
Opened 2022-12-14 11:12 UTC by abhivka7

Signed-off-by: Abhi Kalra <abhivka@amazon.com>

### Description
[Describe what this change achieves]
* Category 
Bug Fix

* Why these changes are required?
Changing logging type to give warning for basic auth with no creds.

* What is the old behavior before changes and new behavior after changes?
When using basic auth without credentials, users just get a message telling "Unauthorized" which is not very descriptive. After the changes users will get a warning telling them there is no Authorization header.

### Issues Resolved
https://github.com/opensearch-project/security/issues/2346

Is this a backport? If so, please add backport PR # and/or commits #
We want to backport it to latest OS versions.

 Signed-off-by: Abhi Kalra <abhivka@amazon.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-15 14:41 UTC, scrawfor99 approved these changes
This seems reasonable.

2022-12-15 15:14 UTC, scrawfor99 requested changes
In light of the previous PR's coversation (https://github.com/opensearch-project/security/pull/2334), I think it may be necessary to first implement a precaution against DoS attacks or justification for why this change cannot wait until such a precaution is in place.

2022-12-20 05:49 UTC, abhivka7 commented
> plement a precaution against DoS attacks

Security plugin does not cover any implementation of precaution against DoS attack. That has to be done from infrastructure change. if needed we can create a backlog to see what can be done from our end. 
Anyways, having a log to tell if there is an attack is still needed and therefore the PR should be merged.

2022-12-20 12:40 UTC, davidlago commented
I'm struggling to see how this is any different than logging any other messages for unauthenticated requests. If you get millions of them, yes, your logs are filling up but also you have other resources under strain as well that will probably be an issue and/or be detected and acted upon (and you might find those logs useful after all?)

Based on @peternied 's comment [here](https://github.com/opensearch-project/security/pull/2334#discussion_r1047333931), perhaps the compromise is to let this type of error log level be configurable, default it to current level and let people override. Right now it seems like OP _is_ already resorting to setting it to trace to be able to see these, which is an even worse scenario if we're thinking of DoS, so adding this as a configurable level will consider all users' needs while preserving our current default behavior.

wdyt?

2022-12-20 14:01 UTC, varun-lodaya commented
I think we should decouple the problem of logs filling up disk from adding more logs, since there are tons of places where we log lack of FGAC permissions at request level or SAML JWT failures for every request. Eg - 

- https://github.com/opensearch-project/security/blob/b836040c577894a08db9377d46a3d4eaca426fb8/src/main/java/com/amazon/dlic/auth/http/jwt/AbstractHTTPJwtAuthenticator.java#L173
- https://github.com/opensearch-project/security/blob/f431ec2201e1466b7c12528347a1f54cf64387c9/src/main/java/org/opensearch/security/configuration/PrivilegesInterceptorImpl.java#L73

Moreover, as @davidlago  mentioned, if a user is sending millions of request, they are probably already stressing other system resources.

2022-12-20 14:06 UTC, cwperks approved these changes

2022-12-20 14:15 UTC, scrawfor99 approved these changes

2022-12-20 16:09 UTC, RyanL1997 approved these changes

2022-12-21 14:16 UTC, merged