Feature branch sync up with main branch
opensearch-project/security pull request #2847
Opened 2023-06-09 14:35 UTC by RyanL1997

### Description
Feature branch sync up with main

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-06-09 14:38 UTC, scrawfor99 commented on gradle/formatting.gradle
> +}
```suggestion
}

```

2023-06-09 14:38 UTC, scrawfor99 commented on formatter/formatterConfig.xml
> +</profiles>
```suggestion
</profiles>

```

2023-06-09 15:02 UTC, DarshitChanpura commented
Are we still pushing changes to this branch?

2023-06-09 15:29 UTC, cwperks commented
@RyanL1997 I am seeing some differences after I did a merge from main -> feature/extensions and resolved conflicts. The file count on this https://github.com/opensearch-project/security/compare/feature/extensions...cwperks:format-feature-extensions-apply?expand=1 is different from this PR.

I checked out your branch and did a merge of main -> this branch and had to resolve the same conflicts from merging main into the branch in the link above.

2023-06-09 16:39 UTC, RyanL1997 commented
> Are we still pushing changes to this branch?

Hi @DarshitChanpura. Yes this [PR](https://github.com/opensearch-project/security/pull/2833) needs the formatting changes + library fix to run the test I think

2023-06-09 17:33 UTC, peternied requested changes
Lets please hold off on these changes , I've still got outstanding commits for this branch that I'd like to land before we pull in all the style changes.

2023-06-13 18:26 UTC, peternied reviewed
I'm no longer impacted by this changes getting merged.  Please use `rebase and merge` instead of `squash and merge` via the GitHub UX so it makes it easier to manage the changes.

2023-06-13 21:44 UTC, RyanL1997 commented
Closing this one due to the merge of: https://github.com/opensearch-project/security/pull/2854

2023-06-13 21:44 UTC, closed without merging