[Enhancement] Add a flag to setup default admin:admin in demo script
opensearch-project/security pull request #3441
Opened 2023-10-03 01:51 UTC by RyanL1997

### Description
[Describe what this change achieves]
* Category (Enhancement, New feature, Bug fix, Test fix, Refactoring, Maintenance, Documentation)
* Why these changes are required?
* What is the old behavior before changes and new behavior after changes?

### Issues Resolved
[List any issues this PR will resolve]

Is this a backport? If so, please add backport PR # and/or commits #

### Testing
[Please provide details of testing done: unit testing, integration testing and manual testing]

### Check List
- [ ] New functionality includes testing
- [ ] New functionality has been documented
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-10-03 02:46 UTC, peternied requested changes
This change lowers the security posture by allow setting the password to a preconfigured value, I feel strongly we should not merge a change of this nature.

2023-10-03 02:57 UTC, RyanL1997 commented
@peternied Thanks for the feedback! Lets move our conversation [here](https://github.com/opensearch-project/opensearch-build/issues/4094). This PR is demo approach of one of the potential solutions that me, @DarshitChanpura  and @peterzhuamazon discussed. Feel free to drop some thoughts on that open issue in build repo.

2023-10-03 14:42 UTC, DarshitChanpura reviewed
@peterzhuamazon shared his perspective from build side and I share the sentiment. Here is an approach that allows us to gradually bring this change in :
1. We allow passing an additional inline argument with `initialAdminPassword`
2. If the argument is not present, we then prompt user during installation script to provide an admin password.
3. (For now) If they choose to not provide password we default it to `admin` with a warning message in next release this option will be removed, and in next release we remove it. (For 2.11 it might be too close to make this call especially with CI builds and RC generation)

2023-10-06 18:41 UTC, peternied commented
I believe there are other options that are being looked into to handle the rollout process around changing the default password.  Lets reopen this change if the rollout process indicates its the path forward.

2023-10-06 18:41 UTC, closed without merging