Update ci.yml to use upload-artifact@v4 for better build time
opensearch-project/security pull request #4170
Opened 2024-03-26 11:28 UTC by nicheexpress

upload-artifact@v4 is 10x faster (according to GitHub), It has significantly reduced build time

https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/

2024-03-26 11:39 UTC, peternied requested changes
Thanks for the contribution, without being paired with the download artifact of the same version this will cause failures.  Please look into a previous pull request [1] that updated this into main.

I recommend creating new pull request following the backport workflow [2] to get this functionality into this 1.3 branch.

- [1] https://github.com/opensearch-project/security/pull/3893
- [2] https://github.com/opensearch-project/security/pull/3893#issuecomment-1867955322

2024-03-26 12:02 UTC, nicheexpress commented
Thanks @peternied, I believe that download-artifact does not exists in 1.3 it was introduced later on

2024-03-26 12:44 UTC, peternied commented
It was added later, in this repository we use backporting workflows [1] to move code from the main branch out to current major versions and minor versions.  If you'd like to get this change into this branch I'd recommend following that process.

Note; since this branch is maintained for security updates.  We've got a high barrier to entry for changes to it - I'm on the fence if your proposed change meets that bar.  If you are looking to make improvements with more impact, I would suggest looking at the `main` branch.

- [1] https://github.com/opensearch-project/.github/blob/main/RELEASING.md#backporting

2024-03-28 07:56 UTC, nicheexpress commented
Thanks @peternied I've learned something new :)
I've opened a new PR by following the guide above

2024-03-28 10:54 UTC, closed without merging